// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMy4vFuYhkyA_hW1DWTdiU_Lc-2MoA5jQ',
    appId: '1:954101074159:web:7e0e5aa6801c299bf5331a',
    messagingSenderId: '954101074159',
    projectId: 'kandi-project',
    authDomain: 'kandi-project.firebaseapp.com',
    storageBucket: 'kandi-project.appspot.com',
    measurementId: 'G-ZMN2MEHZSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcd0uT_nB2VIllHN3UEfw5Rj9XDInMWGQ',
    appId: '1:954101074159:android:1eef3d6deb292b8bf5331a',
    messagingSenderId: '954101074159',
    projectId: 'kandi-project',
    storageBucket: 'kandi-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr4_HDlK_BDCYZcW5zEpkryT1qDAYFg1g',
    appId: '1:954101074159:ios:684ab2a35cbbf6d4f5331a',
    messagingSenderId: '954101074159',
    projectId: 'kandi-project',
    storageBucket: 'kandi-project.appspot.com',
    iosBundleId: 'com.example.kandi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr4_HDlK_BDCYZcW5zEpkryT1qDAYFg1g',
    appId: '1:954101074159:ios:085cae48ef51ce52f5331a',
    messagingSenderId: '954101074159',
    projectId: 'kandi-project',
    storageBucket: 'kandi-project.appspot.com',
    iosBundleId: 'com.example.kandi.RunnerTests',
  );
}
